### ISSUE TITLE
The server does not start

### ISSUE THREAD

**Issue by BazZziliuS** [jmoiron/Gregtech-Extended-Chemistry#3] opened 2024-09-28 16:07 UTC
https://paste.fuix.net/S31sNHs

**Comment by jmoiron** [comment] 2024-09-28 18:07
Does build 17 fix anything?  It should be built against newer gtceu:

https://github.com/jmoiron/Gregtech-Extended-Chemistry/releases/tag/1.20.1-0.1.2-build_17

Having trouble reproducing.

**Comment by jmoiron** [comment] 2024-09-28 18:12
Oh!

If you are using `GT--` and `gtec`, you have to disable GT--'s platline in the configs, otherwise they will both try to modify gtceu materials:

https://github.com/Arborsm/GT--/blob/8d459f1cd2fd4ac35cf9d8ba39260296b7c71840/src/main/java/dev/arbor/gtnn/data/materials/PlatinumLineMaterials.kt#L10

Can you check that the pack has ` "enableHarderPlatinumLine": false` in `gtnn.json`?

**Comment by trulyno** [comment] 2024-09-28 19:05
Disabling that config still gives the error. Is there a naquadah line in gtec that also conflicts with gt--?

**Comment by trulyno** [comment] 2024-09-28 19:18
Nvm I wasn't having the same error. I got the same error after disabling GregTech: Bacteria(which it seems to be incompatible with GTEC because of 'cleanerroom'). After diabling the plat line from GT--, the error disapeared, but game didn't start because of a different error from a different mod. I'll try to fix that then report is the issue will be fixed.

**Comment by trulyno** [comment] 2024-09-28 19:35
Game launches. No issue in game

**Comment by jmoiron** [comment] 2024-09-28 20:03
I will remove `cleanerroom` from a future update, it's there for echo circuits which I don't plan on adding.

**Comment by jmoiron** [comment] 2024-09-28 20:05
99% sure this is the GT-- compatibility bug, going to close this issue as it's fixable with configuration.

**Closed as completed by jmoiron** 2024-09-28 20:05 UTC
